on: [push]

jobs:
  build_deb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tag: [bionic-x86_64, focal-x86_64, stretch-x86_64, buster-x86_64, bullseye-x86_64]
    name: Build ${{ matrix.docker_tag }} deb
    steps:
      - name: Checkout scripts etc
        uses: actions/checkout@v2
      - name: Checkout ripgrep
        uses: actions/checkout@v2
        with:
          repository: 'BurntSushi/ripgrep'
          ref: 'master'
          path: ripgrep
      - name: Build ripgrep
        run: docker run --rm -v $(pwd)/ripgrep:/src -v $(pwd)/scripts:/scripts ghcr.io/rust-cli-apt/dockers:${{ matrix.docker_tag }} x86_64-unknown-linux-gnu
      - name: Archive deb
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ripgrep/target/debian/*.deb
